name: TypeScript Check

on:
  pull_request:

jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc --noEmit || true
